export default {
  id: "chenzk",
  priority: 350,
  alias: "chenzk",
  aliases: [
    "chenzk-api",
    "ezkielyna",
  ],
  display: {
    name: "Chenzk API",
    icon: "hub",
    color: "#10B981",
    textIcon: "CZ",
    website: "https://chenzk.top",
    notice: {
      apiKeyUrl: "https://chenzk.top/token",
    },
  },
  category: "apikey",
  transport: {
    format: "openai",
    baseUrl: "https://chenzk.top/v1/chat/completions",
    validateUrl: "https://chenzk.top/v1/models",
    auth: { combined: true, header: "Authorization", scheme: "bearer" },
  },
  models: [
    { id: "gpt-5.4", name: "GPT 5.4" },
    { id: "gpt-5.4-mini", name: "GPT 5.4 Mini" },
    { id: "gpt-5.4-nano", name: "GPT 5.4 Nano" },
    { id: "gpt-5.2", name: "GPT 5.2" },
    { id: "gpt-5.1", name: "GPT 5.1" },
    { id: "gpt-5", name: "GPT 5" },
    { id: "gpt-5-mini", name: "GPT 5 Mini" },
    { id: "gpt-5-nano", name: "GPT 5 Nano" },
    { id: "gpt-4o", name: "GPT 4o" },
    { id: "gpt-4o-mini", name: "GPT 4o Mini" },
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6" },
    { id: "claude-opus-4-6", name: "Claude Opus 4.6" },
    { id: "deepseek-v3.2", name: "DeepSeek V3.2" },
    { id: "deepseek-r1", name: "DeepSeek R1" },
    { id: "glm-4.7", name: "GLM 4.7" },
    { id: "gpt-image-1", name: "GPT Image 1", params: ["n", "size", "quality", "response_format"], kind: "image" },
  ],
};
