// Generated by scripts/generate-provider-registry.mjs. Do not edit.
// Exclusions:
// - REGISTRY_TEMPLATE.js: template file, not a provider registry entry
// - devin-cli.js: disabled because it spawns a local agent with shell/filesystem access
// - index.js: generated output
// - trae.js: disabled because Trae SOLO does not support tool calling
// - windsurf.js: disabled because its gRPC stream does not handle ToolCallChunk

import providerAlicodeIntl from "./alicode-intl.js";
import providerAlicode from "./alicode.js";
import providerAlimsIntl from "./alims-intl.js";
import providerAnthropic from "./anthropic.js";
import providerAntigravity from "./antigravity.js";
import providerApiAirforce from "./api-airforce.js";
import providerAssemblyai from "./assemblyai.js";
import providerAwsPolly from "./aws-polly.js";
import providerAzure from "./azure.js";
import providerBaidu from "./baidu.js";
import providerBazaarlink from "./bazaarlink.js";
import providerBlackForestLabs from "./black-forest-labs.js";
import providerBlackbox from "./blackbox.js";
import providerBluesminds from "./bluesminds.js";
import providerBraveSearch from "./brave-search.js";
import providerByteplus from "./byteplus.js";
import providerCartesia from "./cartesia.js";
import providerCerebras from "./cerebras.js";
import providerChutes from "./chutes.js";
import providerClaude from "./claude.js";
import providerCline from "./cline.js";
import providerClinepass from "./clinepass.js";
import providerCloudflareAi from "./cloudflare-ai.js";
import providerCodebuddyCn from "./codebuddy-cn.js";
import providerCodebuddyIntl from "./codebuddy-intl.js";
import providerCodex from "./codex.js";
import providerCohere from "./cohere.js";
import providerComfyui from "./comfyui.js";
import providerCommandcode from "./commandcode.js";
import providerCoqui from "./coqui.js";
import providerCursor from "./cursor.js";
import providerDeepgram from "./deepgram.js";
import providerDeepseek from "./deepseek.js";
import providerEdgeTts from "./edge-tts.js";
import providerElevenlabs from "./elevenlabs.js";
import providerExa from "./exa.js";
import providerFalAi from "./fal-ai.js";
import providerFeatherless from "./featherless.js";
import providerFirecrawl from "./firecrawl.js";
import providerFireworks from "./fireworks.js";
import providerGeminiCli from "./gemini-cli.js";
import providerGemini from "./gemini.js";
import providerGithub from "./github.js";
import providerGitlab from "./gitlab.js";
import providerGlmCn from "./glm-cn.js";
import providerGlm from "./glm.js";
import providerGooglePse from "./google-pse.js";
import providerGoogleTts from "./google-tts.js";
import providerGrokCli from "./grok-cli.js";
import providerGrokWeb from "./grok-web.js";
import providerGroq from "./groq.js";
import providerHuggingface from "./huggingface.js";
import providerHyperbolic from "./hyperbolic.js";
import providerIflow from "./iflow.js";
import providerInworld from "./inworld.js";
import providerJinaAi from "./jina-ai.js";
import providerJinaReader from "./jina-reader.js";
import providerKiloGateway from "./kilo-gateway.js";
import providerKilocode from "./kilocode.js";
import providerKimchi from "./kimchi.js";
import providerKimi from "./kimi.js";
import providerKiro from "./kiro.js";
import providerLinkup from "./linkup.js";
import providerLlm7 from "./llm7.js";
import providerLocalDevice from "./local-device.js";
import providerMimoFree from "./mimo-free.js";
import providerMinimaxCn from "./minimax-cn.js";
import providerMinimax from "./minimax.js";
import providerMistral from "./mistral.js";
import providerMmf from "./mmf.js";
import providerMorph from "./morph.js";
import providerNanobanana from "./nanobanana.js";
import providerNebius from "./nebius.js";
import providerNvidia from "./nvidia.js";
import providerOllamaLocal from "./ollama-local.js";
import providerOllama from "./ollama.js";
import providerOpenai from "./openai.js";
import providerOpencodeGo from "./opencode-go.js";
import providerOpencode from "./opencode.js";
import providerOpenrouter from "./openrouter.js";
import providerPerplexityAgent from "./perplexity-agent.js";
import providerPerplexityWeb from "./perplexity-web.js";
import providerPerplexity from "./perplexity.js";
import providerPlayht from "./playht.js";
import providerPoolside from "./poolside.js";
import providerQoder from "./qoder.js";
import providerQoderworkCn from "./qoderwork-cn.js";
import providerQwen from "./qwen.js";
import providerRecraft from "./recraft.js";
import providerRunwayml from "./runwayml.js";
import providerSambanova from "./sambanova.js";
import providerSdwebui from "./sdwebui.js";
import providerSearchapi from "./searchapi.js";
import providerSearxng from "./searxng.js";
import providerSerper from "./serper.js";
import providerSiliconflow from "./siliconflow.js";
import providerStabilityAi from "./stability-ai.js";
import providerTavily from "./tavily.js";
import providerTencent from "./tencent.js";
import providerTogether from "./together.js";
import providerTopaz from "./topaz.js";
import providerTortoise from "./tortoise.js";
import providerVenice from "./venice.js";
import providerVercelAiGateway from "./vercel-ai-gateway.js";
import providerVertexPartner from "./vertex-partner.js";
import providerVertex from "./vertex.js";
import providerVolcengineArk from "./volcengine-ark.js";
import providerVoyageAi from "./voyage-ai.js";
import providerXai from "./xai.js";
import providerXiaomiMimo from "./xiaomi-mimo.js";
import providerXiaomiTokenplan from "./xiaomi-tokenplan.js";
import providerYoucom from "./youcom.js";
import providerZed from "./zed.js";

export default [
  providerAlicodeIntl,
  providerAlicode,
  providerAlimsIntl,
  providerAnthropic,
  providerAntigravity,
  providerApiAirforce,
  providerAssemblyai,
  providerAwsPolly,
  providerAzure,
  providerBaidu,
  providerBazaarlink,
  providerBlackForestLabs,
  providerBlackbox,
  providerBluesminds,
  providerBraveSearch,
  providerByteplus,
  providerCartesia,
  providerCerebras,
  providerChutes,
  providerClaude,
  providerCline,
  providerClinepass,
  providerCloudflareAi,
  providerCodebuddyCn,
  providerCodebuddyIntl,
  providerCodex,
  providerCohere,
  providerComfyui,
  providerCommandcode,
  providerCoqui,
  providerCursor,
  providerDeepgram,
  providerDeepseek,
  providerEdgeTts,
  providerElevenlabs,
  providerExa,
  providerFalAi,
  providerFeatherless,
  providerFirecrawl,
  providerFireworks,
  providerGeminiCli,
  providerGemini,
  providerGithub,
  providerGitlab,
  providerGlmCn,
  providerGlm,
  providerGooglePse,
  providerGoogleTts,
  providerGrokCli,
  providerGrokWeb,
  providerGroq,
  providerHuggingface,
  providerHyperbolic,
  providerIflow,
  providerInworld,
  providerJinaAi,
  providerJinaReader,
  providerKiloGateway,
  providerKilocode,
  providerKimchi,
  providerKimi,
  providerKiro,
  providerLinkup,
  providerLlm7,
  providerLocalDevice,
  providerMimoFree,
  providerMinimaxCn,
  providerMinimax,
  providerMistral,
  providerMmf,
  providerMorph,
  providerNanobanana,
  providerNebius,
  providerNvidia,
  providerOllamaLocal,
  providerOllama,
  providerOpenai,
  providerOpencodeGo,
  providerOpencode,
  providerOpenrouter,
  providerPerplexityAgent,
  providerPerplexityWeb,
  providerPerplexity,
  providerPlayht,
  providerPoolside,
  providerQoder,
  providerQoderworkCn,
  providerQwen,
  providerRecraft,
  providerRunwayml,
  providerSambanova,
  providerSdwebui,
  providerSearchapi,
  providerSearxng,
  providerSerper,
  providerSiliconflow,
  providerStabilityAi,
  providerTavily,
  providerTencent,
  providerTogether,
  providerTopaz,
  providerTortoise,
  providerVenice,
  providerVercelAiGateway,
  providerVertexPartner,
  providerVertex,
  providerVolcengineArk,
  providerVoyageAi,
  providerXai,
  providerXiaomiMimo,
  providerXiaomiTokenplan,
  providerYoucom,
  providerZed,
];
