export default {
  id: "opencode",
  priority: 40,
  hasFree: true,
  alias: "oc",
  uiAlias: "oc",
  display: {
    name: "OpenCode Free",
    icon: "terminal",
    color: "#E87040",
    textIcon: "OC",
  },
  category: "free",
  noAuth: true,
  transport: {
    baseUrl: "https://opencode.ai",
    format: "openai-responses",
    forceStream: true,
    thinkingFormat: "opencode",
    headers: {
      "x-opencode-client": "desktop",
    },
    noAuth: true,
  },
  models: [
    { id: "x-preview-f-free", name: "Ox Alpha Free", targetFormat: "openai", supportedFormats: ["openai"] },
    { id: "ox-alpha-free", name: "Ox Alpha Free", upstreamModelId: "x-preview-f-free", targetFormat: "openai", supportedFormats: ["openai"] },
    { id: "ox-alpha", name: "Ox Alpha", upstreamModelId: "x-preview-f-free", targetFormat: "openai", supportedFormats: ["openai"] },
    { id: "muse-spark-1.2-contributor-free", name: "Muse Spark 1.2 Contributor Free", targetFormat: "openai-responses", supportedFormats: ["openai-responses"] },
    { id: "mimo-v2.5-free", name: "MiMo v2.5 Free", targetFormat: "openai", supportedFormats: ["openai"] },
    { id: "hy3-free", name: "Hunyuan 3 Free", targetFormat: "openai", supportedFormats: ["openai"] },
    { id: "nemotron-3.5-lightning-free", name: "Nemotron 3.5 Lightning Free", targetFormat: "openai", supportedFormats: ["openai"] },
    { id: "nemotron-3-ultra-free", name: "Nemotron 3 Ultra Free", targetFormat: "openai", supportedFormats: ["openai"] },
    { id: "laguna-s-2.1-free", name: "Laguna S 2.1 Free", targetFormat: "openai", supportedFormats: ["openai"] },
  ],
  modelsFetcher: { url: "https://opencode.ai/zen/v1/models", type: "opencode-free" },
  passthroughModels: true,
  transports: [
    { format: "openai-responses", baseUrl: "https://opencode.ai/zen/v1/responses" },
  ],
};
